[package]
name = "testutils"
version = "0.1.0"
authors = ["Mike Zeller <mike@mikezeller.net>"]
edition = "2018"

[dependencies]
chrono = "0.4.6"
uuid = { version = "0.7.4", features = ["v4"] }
vminfod = { path = "../vminfod" }
rand = "0.6.5"
